import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { Printer, X } from "lucide-react";
import type { Product } from "@/lib/store";

interface InvoiceBillProps {
  product: Product | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function InvoiceBill({ product, open, onOpenChange }: InvoiceBillProps) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!product) return null;

  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Invoice - ${product.invoice_number || product.product_name}</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 24px; }
        .header h1 { font-size: 22px; margin: 0; }
        .header p { color: #666; font-size: 13px; margin: 4px 0; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e5e5; font-size: 14px; }
        th { background: #f5f5f5; font-weight: 600; }
        .total { text-align: right; font-size: 18px; font-weight: bold; margin-top: 16px; }
        .footer { text-align: center; margin-top: 40px; color: #999; font-size: 12px; }
      </style></head><body>
      ${content.innerHTML}
      <div class="footer">Generated by InvenTrack · ${new Date().toLocaleDateString()}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const totalAmount = product.bill_amount || product.price * product.quantity;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            Invoice Bill
            <Button size="sm" variant="outline" onClick={handlePrint} className="gap-1">
              <Printer className="h-4 w-4" />
              Print
            </Button>
          </DialogTitle>
        </DialogHeader>

        <div ref={printRef} className="space-y-4">
          <div className="header text-center">
            <h1 className="text-xl font-bold text-foreground">INVOICE</h1>
            {product.invoice_number && (
              <p className="text-sm text-muted-foreground">#{product.invoice_number}</p>
            )}
          </div>

          <Separator />

          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-muted-foreground">Supplier</p>
              <p className="font-medium text-foreground">{product.supplier_name || "N/A"}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Date</p>
              <p className="font-medium text-foreground">{product.date_added}</p>
            </div>
            {product.vendor_gst && (
              <div>
                <p className="text-muted-foreground">Vendor GST</p>
                <p className="font-medium text-foreground">{product.vendor_gst}</p>
              </div>
            )}
            <div>
              <p className="text-muted-foreground">Category</p>
              <p className="font-medium text-foreground">{product.category}</p>
            </div>
          </div>

          <Separator />

          <table className="w-full text-sm">
            <thead>
              <tr className="border-b">
                <th className="text-left py-2 text-muted-foreground font-medium">Item</th>
                <th className="text-right py-2 text-muted-foreground font-medium">Qty</th>
                <th className="text-right py-2 text-muted-foreground font-medium">Price</th>
                <th className="text-right py-2 text-muted-foreground font-medium">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b">
                <td className="py-2 text-foreground">{product.product_name}</td>
                <td className="text-right py-2 text-foreground">{product.quantity}</td>
                <td className="text-right py-2 text-foreground">₹{product.price.toFixed(2)}</td>
                <td className="text-right py-2 text-foreground">₹{(product.price * product.quantity).toFixed(2)}</td>
              </tr>
            </tbody>
          </table>

          <div className="flex justify-end">
            <div className="text-right">
              <p className="text-sm text-muted-foreground">Bill Amount</p>
              <p className="text-2xl font-bold text-foreground">₹{totalAmount.toFixed(2)}</p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
